package database

var schemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS models (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL,
		alias TEXT NOT NULL UNIQUE,
		max_preset TEXT,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	);`,
	`CREATE TABLE IF NOT EXISTS model_presets (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		model_id INTEGER NOT NULL,
		value TEXT NOT NULL,
		position INTEGER NOT NULL DEFAULT 0,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		FOREIGN KEY (model_id) REFERENCES models(id) ON DELETE CASCADE,
		UNIQUE(model_id, value)
	);`,
	`CREATE INDEX IF NOT EXISTS idx_model_presets_model ON model_presets(model_id);`,
	`CREATE TABLE IF NOT EXISTS settings (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		fan_min_count INTEGER,
		fan_min_duty INTEGER,
		fan_max_duty INTEGER,
		cooling_mode TEXT NOT NULL DEFAULT 'auto',
		ignore_broken_sensors INTEGER NOT NULL DEFAULT 0,
		min_operational_chains INTEGER,
		preset TEXT,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	);`,
	`CREATE TABLE IF NOT EXISTS settings_pools (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		settings_id INTEGER NOT NULL,
		position INTEGER NOT NULL DEFAULT 0,
		url TEXT NOT NULL,
		username TEXT,
		password TEXT,
		FOREIGN KEY (settings_id) REFERENCES settings(id) ON DELETE CASCADE
	);`,
	`CREATE INDEX IF NOT EXISTS idx_settings_pools_settings ON settings_pools(settings_id);`,
	`CREATE TABLE IF NOT EXISTS miners (
		id TEXT PRIMARY KEY,
		ip TEXT,
		api_key TEXT,
		managed INTEGER NOT NULL DEFAULT 0,
		unlock_pass TEXT NOT NULL DEFAULT 'admin',
		model_id INTEGER,
		settings_id INTEGER,
		latest_status_id INTEGER,
		created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		FOREIGN KEY (model_id) REFERENCES models(id) ON DELETE SET NULL,
		FOREIGN KEY (settings_id) REFERENCES settings(id) ON DELETE SET NULL
	);`,
	`CREATE INDEX IF NOT EXISTS idx_miners_model ON miners(model_id);`,
	`CREATE INDEX IF NOT EXISTS idx_miners_settings ON miners(settings_id);`,
	`CREATE INDEX IF NOT EXISTS idx_miners_latest_status ON miners(latest_status_id);`,
	`CREATE TABLE IF NOT EXISTS statuses (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		miner_id TEXT NOT NULL,
		uptime INTEGER,
		state TEXT,
		preset TEXT,
		hashrate REAL,
		power_usage REAL,
		power_consumption REAL,
		recorded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		FOREIGN KEY (miner_id) REFERENCES miners(id) ON DELETE CASCADE
	);`,
	`CREATE INDEX IF NOT EXISTS idx_statuses_miner ON statuses(miner_id, recorded_at DESC);`,
	`ALTER TABLE statuses ADD COLUMN preset TEXT;`,
	`ALTER TABLE statuses ADD COLUMN power_usage REAL;`,
	`ALTER TABLE statuses ADD COLUMN power_consumption REAL;`,
	`CREATE TABLE IF NOT EXISTS status_fans (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		status_id INTEGER NOT NULL,
		fan_identifier TEXT,
		rpm INTEGER,
		status TEXT,
		FOREIGN KEY (status_id) REFERENCES statuses(id) ON DELETE CASCADE
	);`,
	`CREATE INDEX IF NOT EXISTS idx_status_fans_status ON status_fans(status_id);`,
	`CREATE TABLE IF NOT EXISTS chain_snapshots (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		miner_id TEXT NOT NULL,
		status_id INTEGER,
		chain_identifier TEXT,
		state TEXT,
		hashrate REAL,
		pcb_temp_min REAL,
		pcb_temp_max REAL,
		chip_temp_min REAL,
		chip_temp_max REAL,
		recorded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		FOREIGN KEY (miner_id) REFERENCES miners(id) ON DELETE CASCADE,
		FOREIGN KEY (status_id) REFERENCES statuses(id) ON DELETE CASCADE
	);`,
	`ALTER TABLE chain_snapshots ADD COLUMN pcb_temp_min REAL;`,
	`ALTER TABLE chain_snapshots ADD COLUMN pcb_temp_max REAL;`,
	`ALTER TABLE chain_snapshots ADD COLUMN chip_temp_min REAL;`,
	`ALTER TABLE chain_snapshots ADD COLUMN chip_temp_max REAL;`,
	`CREATE INDEX IF NOT EXISTS idx_chain_snapshots_miner ON chain_snapshots(miner_id, recorded_at DESC);`,
	`CREATE TABLE IF NOT EXISTS chain_chips (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		chain_snapshot_id INTEGER NOT NULL,
		chip_identifier TEXT,
		hashrate REAL,
		temperature REAL,
		FOREIGN KEY (chain_snapshot_id) REFERENCES chain_snapshots(id) ON DELETE CASCADE
	);`,
	`CREATE INDEX IF NOT EXISTS idx_chain_chips_snapshot ON chain_chips(chain_snapshot_id);`,
	`ALTER TABLE model_presets ADD COLUMN expected_power_w REAL;`,
	`CREATE TABLE IF NOT EXISTS plant_readings (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		plant_id TEXT NOT NULL,
		total_generation REAL NOT NULL,
		total_container_consumption REAL NOT NULL,
		available_power REAL NOT NULL,
		raw_data TEXT,
		recorded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	);`,
	`CREATE INDEX IF NOT EXISTS idx_plant_readings_recorded ON plant_readings(recorded_at DESC);`,
	`ALTER TABLE plant_readings ADD COLUMN generation_sources TEXT;`,
	`ALTER TABLE plant_readings ADD COLUMN consumption_sources TEXT;`,
	`CREATE TABLE IF NOT EXISTS power_balance_events (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		miner_id TEXT NOT NULL,
		old_preset TEXT,
		new_preset TEXT,
		old_power REAL,
		new_power REAL,
		reason TEXT NOT NULL,
		total_consumption_before REAL,
		total_consumption_after REAL,
		available_power REAL,
		target_power REAL,
		success INTEGER NOT NULL DEFAULT 1,
		error_message TEXT,
		recorded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		FOREIGN KEY (miner_id) REFERENCES miners(id) ON DELETE CASCADE
	);`,
	`CREATE INDEX IF NOT EXISTS idx_power_balance_events_miner ON power_balance_events(miner_id, recorded_at DESC);`,
	`CREATE INDEX IF NOT EXISTS idx_power_balance_events_recorded ON power_balance_events(recorded_at DESC);`,
	`CREATE TABLE IF NOT EXISTS app_settings (
		key TEXT PRIMARY KEY,
		value TEXT NOT NULL,
		updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	);`,
	`INSERT OR IGNORE INTO app_settings (key, value) VALUES ('safety_margin_percent', '10.0');`,
	`INSERT OR IGNORE INTO app_settings (key, value) VALUES ('last_preset_change', '{}');`,
}
